name: PR Review Flow

on:
  pull_request_review:

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        if: github.event.review.state == 'changes_requested'
        with:
          remove-labels: "ready-for-review"
